spec-version: 0.30.0
name: lentil
author: Patrick D. Elliott
maintainer: patrick.d.elliott@gmail.com
license: MIT

build-type: Simple

source-dirs: src
dependencies:
- { name: "base", version: '>=4.12 && <4.13' }

ghc-options: -Wall
library: {}
executable:
  main: Main.hs
