spec-version: 0.30.0
name: lentil
author: Patrick D. Elliott
maintainer: patrick.d.elliott@gmail.com
license: MIT

build-type: Simple

dependencies:
- { name: "base", version: '>=4.9.1.0 && <5' }
- { name: "dhall", version: '^>=1.32.0' }
- { name: "pandoc" }
- { name: "clay" }
- { name: "blaze-html" }
- { name: "shake" }
- { name: "text" }
- { name: "filepath" }
- { name: "containers" }
- { name: "time" }


source-dirs: src

ghc-options: [-Wall, -threaded]

library: {}
executable:
  main: Main.hs
