spec-version: 0.30.0
name: lentil
author: Patrick D. Elliott
maintainer: patrick.d.elliott@gmail.com
license: MIT

build-type: Simple

source-dirs: app
dependencies:
- { name: "base", version: '>=4.12 && <4.13' }
- { name: "dhall", version: '^>=1.32.0' }

ghc-options: -Wall
executable:
  main: Main.hs
