spec-version: 0.30.0
name: lentil
author: Patrick D. Elliott
version: 0.0.0
maintainer: patrick.d.elliott@gmail.com
license: MIT

build-type: Simple

dependencies:
- { name: "base", version: '>=4.9.1.0 && <5' }
- { name: "dhall", version: '^>=1.32.0' }
- { name: "pandoc" }
- { name: "pandoc-citeproc" }
- { name: "clay" }
- { name: "blaze-html" }
- { name: "shake" }
- { name: "text" }
- { name: "wai-app-static" }
- { name: "warp" }
- { name: "containers" }


source-dirs: src

ghc-options:
  - -Wall
  - -threaded
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

default-extensions:
  - EmptyCase
  - FlexibleContexts
  - FlexibleInstances
  - InstanceSigs
  - MultiParamTypeClasses
  - LambdaCase
  - MultiWayIf
  - NamedFieldPuns
  - TupleSections
  - OverloadedStrings
  - ScopedTypeVariables
  - DeriveGeneric
  - GeneralizedNewtypeDeriving
  - DerivingStrategies

library: {}
executable:
  main: Main.hs
